
services:
  # Service Base de Données MySQL
  mysql:
    image: mysql:8.0
    container_name: agile-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Correspond à spring.datasource.password
      MYSQL_DATABASE: agile      # Correspond à spring.datasource.url
    ports:
      - "3306:3306"              # Mappe le port 3306 du conteneur vers localhost:3306
    volumes:
      - mysql_data:/var/lib/mysql # Pour garder les données même si tu éteins le conteneur
    # Commande pour éviter les erreurs d'authentification avec certains drivers Java
    command: --default-authentication-plugin=mysql_native_password

  # Interface Graphique (Optionnel mais très utile)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: agile-phpmyadmin
    restart: always
    links:
      - mysql:db
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"

volumes:
  mysql_data: